import { UserProfile, VirtualGift, StreamSession, ShortVideo } from './types';

export const CURRENT_USER: UserProfile = {
  id: 'user_me',
  name: 'Alex Rivera',
  handle: '@alexstream',
  email: 'joyiwalehin@gmail.com',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  country: 'United States',
  countryFlag: '🇺🇸',
  language: 'English',
  bio: 'International DJ & tech nomad. Streaming music & gaming daily! ✨',
  followers: 48200,
  diamonds: 18500,
  coins: 4500,
  isVerified: true,
  level: 34,
};

export const AVAILABLE_GIFTS: VirtualGift[] = [
  { id: 'gift_rose', name: 'Cosmic Rose', icon: '🌹', coinPrice: 5, animationType: 'rose', color: '#ff2d55' },
  { id: 'gift_heart', name: 'Heart Sparkle', icon: '💖', coinPrice: 20, animationType: 'heart', color: '#ff69b4' },
  { id: 'gift_crown', name: 'Champion Crown', icon: '👑', coinPrice: 199, animationType: 'heart', color: '#eab308' },
  { id: 'gift_fireworks', name: 'Neon Fireworks', icon: '🎆', coinPrice: 99, animationType: 'fireworks', color: '#ffd700' },
  { id: 'gift_rocket', name: 'Hypersonic Rocket', icon: '🚀', coinPrice: 799, animationType: 'fireworks', color: '#ec4899' },
  { id: 'gift_supercar', name: 'Cyber Roadster', icon: '🏎️', coinPrice: 499, animationType: 'supercar', color: '#00f2fe' },
  { id: 'gift_galaxy', name: 'Galaxy Portal', icon: '🌌', coinPrice: 1299, animationType: 'galaxy', color: '#7f00ff' },
  { id: 'gift_dragon', name: 'Golden Dragon', icon: '🐉', coinPrice: 2999, animationType: 'dragon', color: '#f7971e' },
];

export const OPPONENT_CREATORS: UserProfile[] = [
  {
    id: 'creator_tokyo',
    name: 'Yuki Tanaka',
    handle: '@yuki_beats',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    country: 'Japan',
    countryFlag: '🇯🇵',
    language: 'Japanese',
    bio: 'Tokyo Synthwave & Electro producer 🎧',
    followers: 129000,
    diamonds: 89400,
    coins: 12000,
    level: 42,
    isVerified: true,
  },
  {
    id: 'creator_rio',
    name: 'Camila Santos',
    handle: '@camilasamba',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    country: 'Brazil',
    countryFlag: '🇧🇷',
    language: 'Portuguese',
    bio: 'Bossa & Pop singer from Rio! 🇧🇷✨',
    followers: 95400,
    diamonds: 64200,
    coins: 8400,
    level: 38,
    isVerified: true,
  },
  {
    id: 'creator_paris',
    name: 'Luc Dupont',
    handle: '@luc_paris',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    country: 'France',
    countryFlag: '🇫🇷',
    language: 'French',
    bio: 'French Chef & acoustic guitar vibes 🥐🎸',
    followers: 67000,
    diamonds: 32000,
    coins: 5200,
    level: 29,
  },
  {
    id: 'creator_seoul',
    name: 'Min-ho Park',
    handle: '@minho_dance',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    country: 'South Korea',
    countryFlag: '🇰🇷',
    language: 'Korean',
    bio: 'K-pop dance freestyle & choreography coach ⚡',
    followers: 210000,
    diamonds: 145000,
    coins: 35000,
    level: 56,
    isVerified: true,
  },
];

export const INITIAL_STREAMS: StreamSession[] = [
  {
    id: 'stream_1',
    title: '🔥 GLOBAL PK BATTLE: Tokyo vs NYC Synth Showcase!',
    creator: OPPONENT_CREATORS[0],
    category: 'Music & Dance',
    viewerCount: 8420,
    likesCount: 52300,
    isLive: true,
    isPrivate: false,
    coverImage: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&auto=format&fit=crop&q=80',
    tags: ['LivePK', 'Electronic', 'Synthwave', 'Global'],
    totalDiamondsEarned: 24800,
    durationSeconds: 1840,
    guests: [
      {
        id: 'guest_1',
        user: OPPONENT_CREATORS[2],
        mode: 'video',
        isMuted: false,
        isVideoOff: false,
      }
    ],
    pkBattle: {
      isActive: true,
      opponent: OPPONENT_CREATORS[1],
      timeRemainingSeconds: 135,
      playerScore: 1420,
      opponentScore: 1190,
      status: 'battling',
      punishmentRule: 'Loser does 20 pushups and sings in Spanish!',
      topSupporterMe: { name: 'Elena_V', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100', coins: 500 },
      topSupporterOpponent: { name: 'Lucas_99', avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100', coins: 450 },
    }
  },
  {
    id: 'stream_2',
    title: '☕ Acoustic Sunset Session & Intimate Chat [Private Room]',
    creator: OPPONENT_CREATORS[1],
    category: 'Music & Dance',
    viewerCount: 1420,
    likesCount: 18900,
    isLive: true,
    isPrivate: true,
    privatePasscode: 'VIP777',
    entryCoinFee: 50,
    coverImage: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80',
    tags: ['Acoustic', 'VIP', 'PrivateLive', 'Chill'],
    totalDiamondsEarned: 15400,
    durationSeconds: 2450,
    guests: []
  },
  {
    id: 'stream_3',
    title: '⚡ K-Pop Freestyle Dance Battle Training Live',
    creator: OPPONENT_CREATORS[3],
    category: 'Fitness',
    viewerCount: 12500,
    likesCount: 92400,
    isLive: true,
    isPrivate: false,
    coverImage: 'https://images.unsplash.com/photo-1547153760-18fc86324498?w=600&auto=format&fit=crop&q=80',
    tags: ['Dance', 'Kpop', 'LivePK', 'Workout'],
    totalDiamondsEarned: 41200,
    durationSeconds: 3200,
    guests: []
  },
  {
    id: 'stream_4',
    title: '🥐 Late Night French Pastry Masterclass & Q&A',
    creator: OPPONENT_CREATORS[2],
    category: 'Cooking',
    viewerCount: 3890,
    likesCount: 24100,
    isLive: true,
    isPrivate: false,
    coverImage: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&auto=format&fit=crop&q=80',
    tags: ['Baking', 'Paris', 'Cooking', 'Multilingual'],
    totalDiamondsEarned: 9800,
    durationSeconds: 1520,
    guests: []
  }
];

export const INITIAL_SHORTS: ShortVideo[] = [
  {
    id: 'short_1',
    creator: OPPONENT_CREATORS[0],
    description: 'Electric neon nights in Shibuya! Which track should I play during tonight’s PK battle? 🚀🇯🇵',
    tags: ['TokyoVibes', 'Synthesizer', 'Nightlife', 'EDM'],
    audioTitle: 'Yuki - Neon Highway (Original Mix)',
    likes: 42100,
    commentsCount: 1280,
    shares: 890,
    originalLanguage: 'Japanese',
    translatedDescription: 'Electric neon nights in Shibuya! Which track should I play during tonight’s PK battle? 🚀🇯🇵'
  },
  {
    id: 'short_2',
    creator: OPPONENT_CREATORS[3],
    description: 'Quick 15-second footwork tutorial! Tag a dancer who needs to try this drop 🔥',
    tags: ['DanceChallenge', 'KpopDance', 'Tutorial', 'StreamFlow'],
    audioTitle: 'Speed Up - Cyber Pop Groove',
    likes: 98400,
    commentsCount: 3410,
    shares: 4120,
    originalLanguage: 'Korean',
  },
  {
    id: 'short_3',
    creator: OPPONENT_CREATORS[1],
    description: 'Acústico na praia ao entardecer no Rio de Janeiro. Deixe seu coração se inspirar! 🌊✨',
    tags: ['BossaNova', 'RioDeJaneiro', 'AcousticVibes'],
    audioTitle: 'Camila - Ondas Suaves (Live Session)',
    likes: 56700,
    commentsCount: 1940,
    shares: 1250,
    originalLanguage: 'Portuguese',
  }
];

export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'es', name: 'Spanish (Español)', flag: '🇪🇸' },
  { code: 'ja', name: 'Japanese (日本語)', flag: '🇯🇵' },
  { code: 'ko', name: 'Korean (한국어)', flag: '🇰🇷' },
  { code: 'fr', name: 'French (Français)', flag: '🇫🇷' },
  { code: 'pt', name: 'Portuguese (Português)', flag: '🇧🇷' },
  { code: 'zh', name: 'Chinese (中文)', flag: '🇨🇳' },
  { code: 'ar', name: 'Arabic (العربية)', flag: '🇸🇦' },
  { code: 'de', name: 'German (Deutsch)', flag: '🇩🇪' },
];
